/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lumue.mdresolver.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.lumue.mdresolver.client.model.Actor;
import io.github.lumue.mdresolver.client.model.MovieMetadataDuration;
import io.github.lumue.mdresolver.client.model.Tag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.github.lumue.mdresolver.client.invoker.JSON;


/**
 * MovieMetadata
 */
@JsonPropertyOrder({
  MovieMetadata.JSON_PROPERTY_TITLE,
  MovieMetadata.JSON_PROPERTY_DESCRIPTION,
  MovieMetadata.JSON_PROPERTY_TAGS,
  MovieMetadata.JSON_PROPERTY_ACTORS,
  MovieMetadata.JSON_PROPERTY_DURATION,
  MovieMetadata.JSON_PROPERTY_VIEWS,
  MovieMetadata.JSON_PROPERTY_DOWNLOADED,
  MovieMetadata.JSON_PROPERTY_UPLOADED,
  MovieMetadata.JSON_PROPERTY_UPLOADER,
  MovieMetadata.JSON_PROPERTY_SOURCE,
  MovieMetadata.JSON_PROPERTY_SOURCE_ID,
  MovieMetadata.JSON_PROPERTY_SOURCE_U_R_L,
  MovieMetadata.JSON_PROPERTY_RESOLUTION,
  MovieMetadata.JSON_PROPERTY_VOTES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-17T07:38:54.534969731+01:00[Europe/Berlin]")
public class MovieMetadata {
  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private Set<Tag> tags = null;

  public static final String JSON_PROPERTY_ACTORS = "actors";
  private Set<Actor> actors = null;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private MovieMetadataDuration duration;

  public static final String JSON_PROPERTY_VIEWS = "views";
  private Integer views;

  public static final String JSON_PROPERTY_DOWNLOADED = "downloaded";
  private OffsetDateTime downloaded;

  public static final String JSON_PROPERTY_UPLOADED = "uploaded";
  private OffsetDateTime uploaded;

  public static final String JSON_PROPERTY_UPLOADER = "uploader";
  private String uploader;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private String source;

  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  private String sourceId;

  public static final String JSON_PROPERTY_SOURCE_U_R_L = "sourceURL";
  private String sourceURL;

  public static final String JSON_PROPERTY_RESOLUTION = "resolution";
  private Integer resolution;

  public static final String JSON_PROPERTY_VOTES = "votes";
  private Integer votes;


  public MovieMetadata title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public MovieMetadata description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public MovieMetadata tags(Set<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public MovieMetadata addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new LinkedHashSet<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Tag> getTags() {
    return tags;
  }


  public void setTags(Set<Tag> tags) {
    this.tags = tags;
  }


  public MovieMetadata actors(Set<Actor> actors) {
    this.actors = actors;
    return this;
  }

  public MovieMetadata addActorsItem(Actor actorsItem) {
    if (this.actors == null) {
      this.actors = new LinkedHashSet<>();
    }
    this.actors.add(actorsItem);
    return this;
  }

   /**
   * Get actors
   * @return actors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<Actor> getActors() {
    return actors;
  }


  public void setActors(Set<Actor> actors) {
    this.actors = actors;
  }


  public MovieMetadata duration(MovieMetadataDuration duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MovieMetadataDuration getDuration() {
    return duration;
  }


  public void setDuration(MovieMetadataDuration duration) {
    this.duration = duration;
  }


  public MovieMetadata views(Integer views) {
    this.views = views;
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VIEWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getViews() {
    return views;
  }


  public void setViews(Integer views) {
    this.views = views;
  }


  public MovieMetadata downloaded(OffsetDateTime downloaded) {
    this.downloaded = downloaded;
    return this;
  }

   /**
   * Get downloaded
   * @return downloaded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOWNLOADED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDownloaded() {
    return downloaded;
  }


  public void setDownloaded(OffsetDateTime downloaded) {
    this.downloaded = downloaded;
  }


  public MovieMetadata uploaded(OffsetDateTime uploaded) {
    this.uploaded = uploaded;
    return this;
  }

   /**
   * Get uploaded
   * @return uploaded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPLOADED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUploaded() {
    return uploaded;
  }


  public void setUploaded(OffsetDateTime uploaded) {
    this.uploaded = uploaded;
  }


  public MovieMetadata uploader(String uploader) {
    this.uploader = uploader;
    return this;
  }

   /**
   * Get uploader
   * @return uploader
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPLOADER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUploader() {
    return uploader;
  }


  public void setUploader(String uploader) {
    this.uploader = uploader;
  }


  public MovieMetadata source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  public void setSource(String source) {
    this.source = source;
  }


  public MovieMetadata sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceId() {
    return sourceId;
  }


  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }


  public MovieMetadata sourceURL(String sourceURL) {
    this.sourceURL = sourceURL;
    return this;
  }

   /**
   * Get sourceURL
   * @return sourceURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceURL() {
    return sourceURL;
  }


  public void setSourceURL(String sourceURL) {
    this.sourceURL = sourceURL;
  }


  public MovieMetadata resolution(Integer resolution) {
    this.resolution = resolution;
    return this;
  }

   /**
   * Get resolution
   * @return resolution
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESOLUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getResolution() {
    return resolution;
  }


  public void setResolution(Integer resolution) {
    this.resolution = resolution;
  }


  public MovieMetadata votes(Integer votes) {
    this.votes = votes;
    return this;
  }

   /**
   * Get votes
   * @return votes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVotes() {
    return votes;
  }


  public void setVotes(Integer votes) {
    this.votes = votes;
  }


  /**
   * Return true if this MovieMetadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieMetadata movieMetadata = (MovieMetadata) o;
    return Objects.equals(this.title, movieMetadata.title) &&
        Objects.equals(this.description, movieMetadata.description) &&
        Objects.equals(this.tags, movieMetadata.tags) &&
        Objects.equals(this.actors, movieMetadata.actors) &&
        Objects.equals(this.duration, movieMetadata.duration) &&
        Objects.equals(this.views, movieMetadata.views) &&
        Objects.equals(this.downloaded, movieMetadata.downloaded) &&
        Objects.equals(this.uploaded, movieMetadata.uploaded) &&
        Objects.equals(this.uploader, movieMetadata.uploader) &&
        Objects.equals(this.source, movieMetadata.source) &&
        Objects.equals(this.sourceId, movieMetadata.sourceId) &&
        Objects.equals(this.sourceURL, movieMetadata.sourceURL) &&
        Objects.equals(this.resolution, movieMetadata.resolution) &&
        Objects.equals(this.votes, movieMetadata.votes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, tags, actors, duration, views, downloaded, uploaded, uploader, source, sourceId, sourceURL, resolution, votes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieMetadata {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    actors: ").append(toIndentedString(actors)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    downloaded: ").append(toIndentedString(downloaded)).append("\n");
    sb.append("    uploaded: ").append(toIndentedString(uploaded)).append("\n");
    sb.append("    uploader: ").append(toIndentedString(uploader)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    sourceURL: ").append(toIndentedString(sourceURL)).append("\n");
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("    votes: ").append(toIndentedString(votes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

