/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lumue.mdresolver.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.lumue.mdresolver.client.model.MovieMetadataDurationDuration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MovieMetadataDurationUnits
 */
public class MovieMetadataDurationUnitsTest {
    private final MovieMetadataDurationUnits model = new MovieMetadataDurationUnits();

    /**
     * Model tests for MovieMetadataDurationUnits
     */
    @Test
    public void testMovieMetadataDurationUnits() {
        // TODO: test MovieMetadataDurationUnits
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'dateBased'
     */
    @Test
    public void dateBasedTest() {
        // TODO: test dateBased
    }

    /**
     * Test the property 'timeBased'
     */
    @Test
    public void timeBasedTest() {
        // TODO: test timeBased
    }

    /**
     * Test the property 'durationEstimated'
     */
    @Test
    public void durationEstimatedTest() {
        // TODO: test durationEstimated
    }

}
