/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lumue.mdresolver.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.lumue.mdresolver.client.model.MovieMetadataDurationUnits;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MovieMetadataDuration
 */
public class MovieMetadataDurationTest {
    private final MovieMetadataDuration model = new MovieMetadataDuration();

    /**
     * Model tests for MovieMetadataDuration
     */
    @Test
    public void testMovieMetadataDuration() {
        // TODO: test MovieMetadataDuration
    }

    /**
     * Test the property 'seconds'
     */
    @Test
    public void secondsTest() {
        // TODO: test seconds
    }

    /**
     * Test the property 'zero'
     */
    @Test
    public void zeroTest() {
        // TODO: test zero
    }

    /**
     * Test the property 'negative'
     */
    @Test
    public void negativeTest() {
        // TODO: test negative
    }

    /**
     * Test the property 'nano'
     */
    @Test
    public void nanoTest() {
        // TODO: test nano
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

}
