/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lumue.mdresolver.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.lumue.mdresolver.client.model.Actor;
import io.github.lumue.mdresolver.client.model.MovieMetadataDuration;
import io.github.lumue.mdresolver.client.model.Tag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MovieMetadata
 */
public class MovieMetadataTest {
    private final MovieMetadata model = new MovieMetadata();

    /**
     * Model tests for MovieMetadata
     */
    @Test
    public void testMovieMetadata() {
        // TODO: test MovieMetadata
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'actors'
     */
    @Test
    public void actorsTest() {
        // TODO: test actors
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'views'
     */
    @Test
    public void viewsTest() {
        // TODO: test views
    }

    /**
     * Test the property 'downloaded'
     */
    @Test
    public void downloadedTest() {
        // TODO: test downloaded
    }

    /**
     * Test the property 'uploaded'
     */
    @Test
    public void uploadedTest() {
        // TODO: test uploaded
    }

    /**
     * Test the property 'uploader'
     */
    @Test
    public void uploaderTest() {
        // TODO: test uploader
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'sourceURL'
     */
    @Test
    public void sourceURLTest() {
        // TODO: test sourceURL
    }

    /**
     * Test the property 'resolution'
     */
    @Test
    public void resolutionTest() {
        // TODO: test resolution
    }

    /**
     * Test the property 'votes'
     */
    @Test
    public void votesTest() {
        // TODO: test votes
    }

}
