/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.lumue.mdresolver.client.api;

import io.github.lumue.mdresolver.client.invoker.ApiException;
import io.github.lumue.mdresolver.client.model.MovieMetadata;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ResolveControllerApi
 */
@Ignore
public class ResolveControllerApiTest {

    private final ResolveControllerApi api = new ResolveControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resolveMetadataforUrlInBodyTest() throws ApiException {
        String url = null;
        MovieMetadata response = 
        api.resolveMetadataforUrlInBody(url);
        
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resolveMetadataforUrlInPathTest() throws ApiException {
        String url = null;
        MovieMetadata response = 
        api.resolveMetadataforUrlInPath(url);
        
        // TODO: test validations
    }
    
}
